### ISSUE TITLE
reconnecting to Balena AP: instruction need update

### ISSUE THREAD

**Issue by pascaljoly** [Ribbit-Network/ribbit-network-frog-hardware#161]
When loosing the wifi connectivity, reconnect to the Balena AP. 
the notes in https://github.com/Ribbit-Network/ribbit-network-frog-sensor/blob/main/hardware/v3/assembly-instructions/5-sensor-placement.md suggest to connect to https://192.168.42.1/ -- in my case, I had to connect to http://192.168.42.1/ to connect to the balena Wireless AP.

**Comment by keenanjohnson** [comment]
Fixed! Thanks!

**Comment by keenanjohnson** [comment]
Thanks @pascaljoly for the docs contribution @all-contributors

**Comment by keenanjohnson** [comment]
@all-contributors please add @pascaljoly for docs
