### ISSUE TITLE
ESP32: Enclosure Updates for ESP32 Based Frog

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-frog-hardware#163]
Hey @eaudiffred !

As we discussed in our team call earlier, I have fairly high confidence in the new processor that we would use for the microcontroller based version of the Frog.

Here is the actual part and link to adafruit: [Adafruit ESP32-S3 Feather with 4MB Flash 2MB PSRAM - STEMMA QT / Qwiic](https://www.adafruit.com/product/5477)

![image](https://user-images.githubusercontent.com/2559382/194435159-9aa4b685-0932-4c5b-a328-a8c33cb76833.png)

**Implementation Notes**

The power connector is a USB Type connector again shown on the left hand side of the image below. I imagine we would want to orient the board such that the power connector faces down like our previous designs

<img width="594" alt="image" src="https://user-images.githubusercontent.com/2559382/194435319-46069bcd-344e-42c1-b79c-1c43a67d9d41.png">

One thing that is a bit annoying is that USBC Power Adapters tend to be fairly large and not designed for outdoor applications, so I'm wondering if it might be worth designing around a [USBC to Barrel Jack to USB C Adapter like this one](https://www.adafruit.com/product/4536)?

Electrically this would be fine, but physically it will be perhaps mechanically wasteful as that adapter is almost the same length as the whole ESP board haha.

Would love any thoughts or opinions there :)

<img width="543" alt="image" src="https://user-images.githubusercontent.com/2559382/194435562-72adc408-c25d-4d7b-8086-73f424e246bd.png">

**Comment by eaudiffred** [comment]
Thanks @keenanjohnson.  One initial question about the power supply.  Are there any USB-C power supply units that will work?  It looks like it's 3V and I think a max on 150mA.  I can look around for something so that we don't have to use an adapter.  If you know it doesn't exist, just let me know and I'll tie in the adapter.

**Comment by eaudiffred** [comment]
Just posting this here for reference.  
![image](https://user-images.githubusercontent.com/88562047/194618891-f0a31535-05e4-4001-9a26-d65169265b50.png)

**Comment by eaudiffred** [comment]
I believe this is a STEP file of the board, but I can't seem to figure out how to download it.  It's my lack of GitHub knowledge I think.
https://github.com/UnexpectedMaker/esp32s3/blob/main/3d%20models/FeatherS3_P4.step

**Comment by eaudiffred** [comment]
Got it!  Remembered the Desktop App.  The board is not in the CAD imports folder.

**Comment by keenanjohnson** [comment]
@eaudiffred ! Any standard 5V Usb C Power Supply should work (where did you see the 3V number)? I've confirmed that here :)

**Comment by eaudiffred** [comment]
@keenanjohnson, ok cool.  That eliminates the need for the adapter, correct?  
I misread the data sheet.  I thought it was limited to 3V, but that is incorrect.

**Comment by keenanjohnson** [comment]
There are adapters, but the USBC plug I've read does less well outdoors overtime than a barrel jack, but perhaps that's not really a problem worth solving for the moment until we are sure we have an issue.

**Comment by eaudiffred** [comment]
I've started to work on the enclosure based on the ESP32 and we will be able to reduce the size significantly.  Here is an initial idea for the model.

![image](https://user-images.githubusercontent.com/88562047/194911980-54789f7f-87a2-49d8-a4c4-197ce5d9ca78.png)
![image](https://user-images.githubusercontent.com/88562047/194912550-f566d95b-e272-412d-8f7d-257d8f796232.png)

**Comment by keenanjohnson** [comment]
Wow this would be excellent if we could take the size down significantly! 

Looking at your renderings, I'm a little bit suspect that there is enough room there for the USBC cable. Unfortunately, the power connector on the cable end is usually quite long. We might need to include that in the model to check out if there is enough space?

This thing [from a common USBC suply](https://www.adafruit.com/product/4298)

![image](https://user-images.githubusercontent.com/2559382/194913359-50afa5f9-cd14-4a73-a561-4a7eaa2979fb.png)

**Comment by eaudiffred** [comment]
@keenanjohnson, good point.  I went ahead and make a model for the USBC supply.  It does cause issues.  We may be able to reduce the width of the enclosure by taking out space between the clips (red circles).  Then rotating the whole board to almost vertical and lengthening the base.  

I think I can squish the depth a little too.  The width and depth adjustments would make the shroud and head incompatible between versions, but I don't see that as a huge problem right now.  The amount of material and time that can be saved seems to be worth the changes.

![image](https://user-images.githubusercontent.com/88562047/194930038-e16c228b-5999-4b24-b884-52154096d205.png)

**Comment by keenanjohnson** [comment]
Yeah, I wouldn't worry about head capability between versions at the moment. 

One thing we could consider is a right-angle USB C adapter? Perhaps this would help us with the cable routing out of the side? 

https://www.adafruit.com/product/4432

![image](https://user-images.githubusercontent.com/2559382/194934631-a2ba2a50-215a-46ba-83f9-1d89b8ab2787.png)

**Comment by eaudiffred** [comment]
Yeah, I was thinking about that and weighing pros and cons of one additional part on the BOM.  I'll model that up too and see what configuration seems to save the most material.

**Comment by eaudiffred** [comment]
I was able to shrink the depth and width a decent amount.  We are able to save quite a bit of material by using this smaller board.  
 
![image](https://user-images.githubusercontent.com/88562047/195409902-64879803-7834-470b-8af5-3b481cc852f6.png)

![image](https://user-images.githubusercontent.com/88562047/195409771-5d2d2d5c-36de-42f1-a050-f01788a97a38.png)

**Comment by eaudiffred** [comment]
@muditprotect3d, now would be a great time to introduce any ideas regarding the hanging mechanisms!  While we are remodeling for the ESP32 we will have lots of opportunity to prototype.  Also, any ideas concerning the enclosure in general is more than welcome!

**Comment by muditprotect3d** [comment]
@eaudiffred sounds good! I will add some to the thread right now

**Comment by muditprotect3d** [comment]
<img width="1405" alt="Screen Shot 2022-10-12 at 1 48 31 PM" src="https://user-images.githubusercontent.com/106998016/195412865-278861cc-e371-4ced-87c4-82b0a3ce27aa.png">

**Comment by muditprotect3d** [comment]
<img width="1401" alt="Screen Shot 2022-10-12 at 1 49 26 PM" src="https://user-images.githubusercontent.com/106998016/195413040-7fe39a01-2691-45f0-86c9-3b06a2d22942.png">
This is another one, basically similar to the last one except would span the entire width of the back of the enclosure

**Comment by muditprotect3d** [comment]
<img width="1351" alt="Screen Shot 2022-10-12 at 1 50 10 PM" src="https://user-images.githubusercontent.com/106998016/195413195-b672fad2-076b-4652-8781-1ecafa9c797e.png">
This one would be a variable one where you could slide the two ends across the channel to fit across any component of varying length

**Comment by muditprotect3d** [comment]
I created it on the shroud but the ideal location would be on the back of the enclosure

**Comment by muditprotect3d** [comment]
<img width="1411" alt="Screen Shot 2022-10-12 at 1 51 38 PM" src="https://user-images.githubusercontent.com/106998016/195413438-d9845fc0-aae6-4ef3-ac1f-c0a9501fb632.png">
These are more simple hooks, but im working on a design right now to make the bottom hook slideable through a channel

**Comment by muditprotect3d** [comment]
Im working on another design this week, and I had some ideas about the enclosure as well I can send in here by end of week

**Comment by eaudiffred** [comment]
@muditprotect3d Awesome work!  Thanks for sharing.  I realize we should document this design work in a separate GitHub issue just to keep projects organized.  I'll open a GitHub issue for Hanging Mechanism Designs, and we can keep developing these ideas in there.  I'll tag you and reference the posts above.  Then we can use this issue for enclosure design related to the ESP32 change.

**Comment by muditprotect3d** [comment]
Reading this thread again, have we considered/thought about using the space tradeoff to include an external battery instead of a power cable? ( Instead of reducing the size of the enclosure, we could use the extra space due to a smaller processor to include an external battery/power source)?

**Comment by keenanjohnson** [comment]
Great question @muditprotect3d! In the future once we create a solar powered version of the frog, we will need a battery, but right now even with the microcontroller, we will need to have an external power source to power things. The power management for a battery system is a bit complex and I think needs to be designed first before we could scope modifying an enclosure around that.

**Comment by eaudiffred** [comment]
I have some prototypes printed and was able to test fit with the main electrical components.  
CAD files can be found [here](https://cad.onshape.com/documents/b3e6eeabf50d585d20f25fc6/w/da7f4373da69947f3d05d9c4/e/634db96a0c5d4c7b0ff00c45).

Here are some pictures comparing V3 and V4:
![image](https://user-images.githubusercontent.com/88562047/197233076-42ee80fb-eeb1-4077-b66d-6a6d89869da1.png)
![image](https://user-images.githubusercontent.com/88562047/197233134-9ac76763-56a6-4882-8ba0-a3fa9f9bf43f.png)
![image](https://user-images.githubusercontent.com/88562047/197233238-81891ff8-c627-4e97-a5d7-5114a3944d0c.png)

Here are some pictures showing the electrical component fit.  
![image](https://user-images.githubusercontent.com/88562047/197233386-0a6e0ab3-2bed-4d08-87d0-4c1bbf4481c2.png)
![image](https://user-images.githubusercontent.com/88562047/197233422-2cddebbc-5acf-414e-99d8-956ace11fd7b.png)
![image](https://user-images.githubusercontent.com/88562047/197233458-080148da-5a6a-4d6d-b958-b500e302b0f7.png)

**Comment by eaudiffred** [comment]
The biggest problem remaining is figuring out the clip design for the ESP32 board.  I still have not gotten a reliable design that has enough flex for repeated use.  I keep snapping the clips when inserting the board on the 1st or second try.  Let me know if anyone has ideas!  The goal here is just to reduce the amount of hardware (screws in this case) needed for the sensor.    

![image](https://user-images.githubusercontent.com/88562047/197233768-dde4a5c3-1189-4102-8346-fc70b437a1ed.png)

**Comment by keenanjohnson** [comment]
Excellent work @eaudiffred ! Were you able to try plugging in the USB C cable while it's in the enclosure? I'm wondering if there will be any problems with the weight of the hanging cable tilting the hanging sensor and allowing more water into the shields at a high angle as the sensor is getting so small and light now. 

Perhaps @muditprotect3d might have some suggestions on the mechanical side for the clips?

**Comment by eaudiffred** [comment]
@keenanjohnson, excellent point on the cable weight.  I just hung the sensor and plugged it in.  It did tilt slightly.  Enough that its worth moving the power cable entry point.

**Comment by eaudiffred** [comment]
I went with a slightly different approach and flipped the ESP32.  
![image](https://user-images.githubusercontent.com/88562047/197362785-b85bb3cf-1b01-42e7-b674-c5aedc52fcbe.png)
![image](https://user-images.githubusercontent.com/88562047/197362798-97f38d88-30ce-4c8d-9f4e-208b236d55e9.png)
![image](https://user-images.githubusercontent.com/88562047/197362808-2c1e16e3-84f5-4881-83c4-0548b9c7a2f8.png)

**Comment by muditprotect3d** [comment]
@keenanjohnson @eaudiffred could we do something with sliding it in and having it be an interference fit? This way the plastic material could hold the circuit in place similar to how the screw holes work? It would essentially be like a sliding compartment that we put the controller into to keep it from moving around, but wouldn't require any clips to flex back and forth

**Comment by eaudiffred** [comment]
@muditprotect3d, Yes that's a great idea!  I think that will actually keep the board more secure and be easier to print.

**Comment by muditprotect3d** [comment]
@eaudiffred Awesome! Would it be useful if I tried to make some CAD models of what I'm thinking here?
I'm also working on the hanging mechanism incorporated into the larger device. I have two tests this week so am a little swamped but will get that done by midweek!

**Comment by eaudiffred** [comment]
@muditprotect3d, yeah that would be great!  Here is the most [recent model](https://cad.onshape.com/documents/b3e6eeabf50d585d20f25fc6/w/da7f4373da69947f3d05d9c4/e/c221edb50cd05a98d22970e2) I have been working on.   

No rush, get those tests out of the way before worrying about this.  Let me know if you run into any blockers or need help on anything.  Good luck on the tests!

**Comment by muditprotect3d** [comment]
<img width="1081" alt="Screen Shot 2022-11-20 at 9 45 54 PM" src="https://user-images.githubusercontent.com/106998016/202952355-d7a380c1-e97a-41b7-8a1e-be76e3607632.png">
putting this here but here is a mockup of the sliding rails for the feather I was talking about

**Comment by eaudiffred** [comment]
Just copying this comment here (from Discord) for reference.
One thing to keep in mind is that the board will need to slide into place, correct?  So there needs to be enough space in the enclosure to drop the board down, and then slide it over.  Hopefully my thinking makes sense.  Let me know if I need to explain via picture.

**Comment by keenanjohnson** [comment]
Great work collaborating all! Is it worth it creating a separate issue for this sliding feature or are you all ok collaborating here in this issue?

**Comment by eaudiffred** [comment]
@keenanjohnson I think we can finish up the sliding feature in this issue and then call it complete.  @muditprotect3d could you share the link to the file you've been editing?

**Comment by muditprotect3d** [comment]
Yes sending now!

**Comment by muditprotect3d** [comment]
https://cad.onshape.com/documents/3d928932fd41fdc8e9fbaac0/w/87262cd35788e1173a2d535a/e/c180c5717ccf65cb0e58b6c0?renderMode=0&uiState=637f02b3c69bdb43ca62accc

**Comment by muditprotect3d** [comment]
I'll make the edits you had suggested by the end of the week and have a final CAD prototype ready to print by EOW. Sorry about the delay on my end with this.

**Comment by eaudiffred** [comment]
@muditprotect3d Looks good!  I copied your work over to the main file and added some fillets and chamfers.  I'll try and get a test print out this week as well.  
![image](https://user-images.githubusercontent.com/88562047/204347057-945a88e9-80e6-42e6-b1aa-66cae1bbeb2a.png)

**Comment by muditprotect3d** [comment]
Awesome! I think the tolerancing may have to be increased but it will be good to get some prints out and see

**Comment by keenanjohnson** [comment]
Yes let me know if you have anything that is ready for a test print as well.

**Comment by keenanjohnson** [comment]
@muditprotect3d I printed the file you sent in Discord and in general, I think it looks great, though there are some issues to sort out. Thanks for your hard work and @eaudiffred for supporting as always!

**Board Doesn't Fit in Slot**

The biggest issue is that the board is too wide to fit in the slots as provided. The 3D model of the board in Onshape must be wrong or the tolerances are too tight. 

Additionally I noticed there isn't too much space to wiggle the board down in line with the slot, even if the slot was the correct width. Perhaps the whole enclosure would need to be wider?

![image](https://user-images.githubusercontent.com/2559382/204472912-0141e53a-eb4d-4be3-9806-a831ac274449.jpeg)

![image](https://user-images.githubusercontent.com/2559382/204473058-369aa312-6d2f-4a93-8982-4930062d0f48.jpeg)

**Cable Bend Radius**
I'm pretty worried about bending the USB cable 180 degrees like this. The cables are generally pretty stiff and I noticed it really puts a lot of tensions on the connector in the USB housing. I'm wondering if it makes more sense to go back to the esp 32 being vertically mounted? If not, we may need a feature to provide strain relief for the cable so it is not transferred to the connector on the board which is not very strong I think.

![image](https://user-images.githubusercontent.com/2559382/204473753-45b81457-7b98-41fa-a7af-cae24a6d20da.jpeg)

**Board Dimensions**

I've include the measurements I took of my board for validation of the dinesnsions from Adafruit's drawings.

![image](https://user-images.githubusercontent.com/2559382/204472759-a40aa9da-4a6e-46fa-a2ed-096d5b3e17e9.jpeg)

![image](https://user-images.githubusercontent.com/2559382/204472786-bb7491de-6019-4459-b1bb-8f7db6cd2c29.jpeg)

**Comment by eaudiffred** [comment]
Great feedback @keenanjohnson, thanks!  I also printed one last night, but I tweaked the dimensions ahead of time.  I was able to get the board to slide in, but it was still a little too tight.  I think 22.7mm, the exact width of the board will work well.  
![image](https://user-images.githubusercontent.com/88562047/204557257-89c2450a-7e8d-4966-8e3d-63d361940970.png)

**Comment by eaudiffred** [comment]
I also think that the slides can be shorter.  Something like this will provide enough support.  The slides are 20mm long in this picture.  
![image](https://user-images.githubusercontent.com/88562047/204557712-ae7285ea-42d0-4ee3-ad72-64f78b630e6a.png)

**Comment by eaudiffred** [comment]
@muditprotect3d great work on the design!  I like how this functions and secures the board.

**Comment by eaudiffred** [comment]
@keenanjohnson, I'm wondering if we should add the 90deg adapter.  I hate to add another piece to the BOM, but I like how much time and material we've been able to save.  

I'm thinking of two other options right now (the 90deg spacer being a 3rd option):
![image](https://user-images.githubusercontent.com/88562047/204567159-a4dca087-c5f1-493e-b442-2a49e62570d9.png)
![image](https://user-images.githubusercontent.com/88562047/204567476-aaa7687a-34dc-4f7a-8f31-59488a64a681.png)

**Comment by muditprotect3d** [comment]
Hey @eaudiffred @keenanjohnson thank you for the feedback! I didn't have a feather with me when making the slots so I was using the measurements on onshape and kind of figured they would be off a little but this is super helpful feedback! @eaudiffred are the edits you mentioned on the main file? I can go ahead and get another test print as well with the 20mm slots

**Comment by muditprotect3d** [comment]
> Great feedback @keenanjohnson, thanks! I also printed one last night, but I tweaked the dimensions ahead of time. I was able to get the board to slide in, but it was still a little too tight. I think 22.7mm, the exact width of the board will work well.
> ![image](https://user-images.githubusercontent.com/88562047/204557257-89c2450a-7e8d-4966-8e3d-63d361940970.png)
we can increase tolerance in the slide then if it was too tight fitting in?

**Comment by eaudiffred** [comment]
@muditprotect3d, Yes.  I put the edits in the main file.

**Comment by muditprotect3d** [comment]
@eaudiffred sounds good! Sorry about the dimensioning issues there. I'll also get a test print going for today

**Comment by eaudiffred** [comment]
@muditprotect3d, no worries!  That's why we test print!  Definitely an iterative process.

**Comment by muditprotect3d** [comment]
I think that could greatly reduce the strain in the wire -- if we want to make it slightly simple in terms of design we could make it tolerances clips against the side of the wall that the wire can be pushed into?

**Comment by muditprotect3d** [comment]
<img width="832" alt="Screen Shot 2022-11-29 at 2 07 08 PM" src="https://user-images.githubusercontent.com/106998016/204622945-1e28e639-74ad-464b-978c-b7800d339058.png">
@eaudiffred in terms of the modular hooks I was thinking of something like this essentially with a similar hook mechanism as the shroud and then have different types of hooks available for the user to print? Not sure if that's what you had in mind but we can talk more during our meeting tomorrow as well!

**Comment by keenanjohnson** [comment]
Do you have any bandwith to take a shot at design of those strain relief clips @muditprotect3d and I could do a test print and assembly?

As for the hanging hooks, not to be annoying, but let's try to keep that discussion separate in #171

**Comment by muditprotect3d** [comment]
@keenanjohnson sorry about that! I have a midterm tomorrow but I can take a shot at those clips right after that if that works?

**Comment by muditprotect3d** [comment]
@keenanjohnson I think @eaudiffred was doing some work on changing the enclosure design for this issue here as well: https://cad.onshape.com/documents/b3e6eeabf50d585d20f25fc6/w/da7f4373da69947f3d05d9c4/e/634db96a0c5d4c7b0ff00c45

**Comment by muditprotect3d** [comment]
<img width="633" alt="Screen Shot 2022-11-29 at 2 42 42 PM" src="https://user-images.githubusercontent.com/106998016/204632244-74a792b6-0e30-445d-942c-7ee04f9f9f2e.png">
I have a test print in process right now for this enclosure structure

**Comment by eaudiffred** [comment]
@keenanjohnson, @muditprotect3d, I've been messing around with the base this morning trying different shapes.  I have some time to build in the strain relief.  I can get it done in the next few hours and have it ready for a test print.  I'll report back when done.

**Comment by muditprotect3d** [comment]
@eaudiffred sounds good! Let me know if there is anything I can help with

**Comment by eaudiffred** [comment]
What do you think of this?
![image](https://user-images.githubusercontent.com/88562047/204648352-bb3942e2-2f08-4f2b-99fd-db406e37c355.png)
There is a hole in the rounded piece for a ziptie.  
![image](https://user-images.githubusercontent.com/88562047/204648510-bb9a816a-66d6-4992-a88a-204a973158bb.png)

**Comment by muditprotect3d** [comment]
That looks great! Do you think it would be worth to include a clip on the wall for the wire here or will this be sufficient for the strain issues
<img width="805" alt="Screen Shot 2022-11-29 at 4 17 10 PM" src="https://user-images.githubusercontent.com/106998016/204649781-aee4ee4b-da35-4285-bead-d921f2e83878.png">

**Comment by eaudiffred** [comment]
Something like this with another ziptie?
![image](https://user-images.githubusercontent.com/88562047/204654959-140b8cfc-78bb-49c6-92b6-e912c6cd3701.png)
The only concern I have is the print quality.  I usually have trouble with small things that over hang.

**Comment by muditprotect3d** [comment]
@eaudiffred that's a good point this would probably end up printing supports under it, not sure if that's worth the pain in such a small enclosed area I agree.

**Comment by damz** [comment]
Are we giving up on being able to stack a GSM modem wing on top of the feather?

**Comment by keenanjohnson** [comment]
It is a good point that routing the cable over the top of the circuit board would make it challenging to stack a cellular feather module on top. Have you identified what the ideal feather module is yet @damz or does that still need an evaluation?

Until we do a test print we still don't know if the strain relief strategy will work (I'll complete this later today hopefully), so we're not totally committed to that direction yet. However, if we haven't finished a good selection for cellular modules, I wouldn't want to hold up the first release here waiting for the cellular parts release quite yet.

We can always revise the enclosure for a cellular module later if needed.

**Comment by eaudiffred** [comment]
I just started a test print on this file.  
[Base - ESP32_V2 (3).zip](https://github.com/Ribbit-Network/ribbit-network-frog-sensor/files/10117985/Base.-.ESP32_V2.3.zip)

I think we can route the cable back over itself to avoid the area above the board.  I'll see what I can make work with this print.

**Comment by damz** [comment]
> Have you identified what the ideal feather module is yet @damz or does that still need an evaluation?

I am currently evaluating the [qTop Adafruit Feather Compatible LTE Cat-M1/NB-IOT/EGPRS GNSS BG96 shield](https://www.iot-bots.com/collections/qtop-cellular/products/qtop-adafruit-feather-compatible-lte-cat-m1-nb-iot-gnss-shield). It would sit on top of the feather.

**Comment by eaudiffred** [comment]
Not great results with the test print.  There isn't enough space to slide the power port into the board.  The cable flexes and fits, but I can't figure out a way to plug it in...
![image](https://user-images.githubusercontent.com/88562047/204845130-c9d81a29-014d-488e-a6ca-a6901829a7e3.png)

I'm back to this option.  The red rectangles are supports for the adapter.  
![image](https://user-images.githubusercontent.com/88562047/204848699-44e3b741-20ea-407c-a7dd-e7b82ff5897f.png)

**Comment by keenanjohnson** [comment]
I printed the latest version and everything looks very good to me! 

![image](https://user-images.githubusercontent.com/2559382/206041453-43f01aa5-a347-4e74-b3b1-1a26de1e5508.jpeg)![image](https://user-images.githubusercontent.com/2559382/206041467-20593bcb-9472-4e8c-a0a6-19ea76ef8e60.jpeg)

My only two points of feedback:

* Two screws seems adequate for holding the esp32, however it was a bit tricky aligning it initially. Perhaps the other two non screw posts could have small bumps that stick up into the two holes on the board to help initially aligned it?
* I noticed the connector wobbles a bit when plugging in, not too concerning l, but perhaps in the future something could be added to prevent that. 

https://user-images.githubusercontent.com/2559382/206041760-e2a2fb6a-5ac0-4d48-be69-0911ffd4b4b0.MOyV

**Comment by keenanjohnson** [comment]
@eaudiffred should we "release" this version of the enclosure and make additional changes as we go? I can create separate issues for the things above if so. 

Do you need help tagging the latest version of the onshape assembly and everything or do you have that covered?

**Comment by muditprotect3d** [comment]
@keenanjohnson do you think we could include the hooks in this release as well?

**Comment by muditprotect3d** [comment]
I think they are ready after a couple of iterations -- but I can also make more edits if needed by the EOW

**Comment by eaudiffred** [comment]
@keenanjohnson, good points.  I added the bumps for alignment. 
I did include a hole in the pad under the 90deg adapter that can fit a ziptie to secure down the adapter.  I have not tested that out yet.  Did it print out ok?  Would a ziptie apply too much downward pressure on the adapter?  
![image](https://user-images.githubusercontent.com/88562047/206100620-cec44bf1-6b6e-4b7f-a874-0e804649bde6.png)
![image](https://user-images.githubusercontent.com/88562047/206100705-8bdab748-8851-4fd1-a7e5-334f7d3b0f09.png)
Another option to stiffen the adapter would be to add in some kind of blocking around the adapter:
![image](https://user-images.githubusercontent.com/88562047/206100949-2c4fd0b0-a392-489f-b0d4-49bcc885df60.png)

**Comment by eaudiffred** [comment]
@keenanjohnson, Yes, I think its ready to be released!  If we make any changes going forward they will be minor.

**Comment by eaudiffred** [comment]
@muditprotect3d, yes.  Let's include these hooks in the release.  The can be added to the build instructions as options for hanging in different situations.

**Comment by eaudiffred** [comment]
> Do you need help tagging the latest version of the onshape assembly and everything or do you have that covered?

@keenanjohnson, what do you mean by tagging the latest version of the Onshape assembly?

**Comment by keenanjohnson** [comment]
Oh I just meant identifying which assembly and branch was the most up to date

**Comment by eaudiffred** [comment]
@keenanjohnson, gotcha!  Yes, it's this one.  Do you remember how to merge it back as the main?
https://cad.onshape.com/documents/b3e6eeabf50d585d20f25fc6/w/da7f4373da69947f3d05d9c4/e/c221edb50cd05a98d22970e2
![image](https://user-images.githubusercontent.com/88562047/206304622-4636b48a-8160-4b02-aaa9-31f248635682.png)

**Comment by keenanjohnson** [comment]
Yup! I can do that tomorrow :)

**Comment by keenanjohnson** [comment]
Ok @eaudiffred I've merged that branch into the main branch. 

<img width="822" alt="image" src="https://user-images.githubusercontent.com/2559382/206609798-49ecea58-74df-46a5-b27b-9e44dc0ce6d6.png">

**Comment by eaudiffred** [comment]
@keenanjohnson @muditprotect3d, I would vote that we close this issue and release V4.  I made one small change to the Head clips this morning, so I can create a PR to get the file changed in the parts file on GitHub.

**Comment by muditprotect3d** [comment]
@eaudiffred I agree! I think we are ready to release the v4

**Comment by keenanjohnson** [comment]
I know in discord there was some discussion on some very minor revisions for the head clips based on printing results. Do we need to add that here and commit new STLs before an official release?

**Comment by eaudiffred** [comment]
@keenanjohnson, yes.  I'll get the revision printed tonight and make sure it fits tomorrow morning. Then I can submit the PR to update the file tomorrow.

**Comment by eaudiffred** [comment]
Opened PR #195 for the upload of the final version of V4-Head.

**Comment by eaudiffred** [comment]
Added some posts that secure the USBC Adapter in place and eliminate the need for a ziptie.  It fits the adapter I used pretty well right now.  
@keenanjohnson, do you have time to print a test to see if it works out?  My only concern is that different adapters might be shaped slightly differently, in which case it would be important to always purchase a specific one.  

![WIN_20230105_19_44_34_Pro](https://user-images.githubusercontent.com/88562047/210919447-0b9167d0-e8cd-4ac8-8f0b-301aa6dd4bba.jpg)
[BaseV4-Test.zip](https://github.com/Ribbit-Network/ribbit-network-frog-hardware/files/10356967/BaseV4-Test.zip)

**Comment by beriberikix** [comment]
Are we concerned about water/snow ingress? Outdoor enclosures usually use [Cable Glands](https://en.wikipedia.org/wiki/Cable_gland) to prevent that, like [this enclosure](https://www.adafruit.com/product/3931). It also has the benefit of allowing you to use a standard cable and pass it through. I found many 3d-printable cable gland on [Thingiverse](https://www.thingiverse.com/search?q=cable+gland&page=1&type=things&sort=relevant) that may be able to incorporate into the design.

**Comment by keenanjohnson** [comment]
@eaudiffred mu test print finished and it feels vastly more secure than without the supports and no zip tie.  The posts take the force of plugging and unplugging nicely which no longer leaves me concerned about breaking the connector on the board.

**Comment by keenanjohnson** [comment]
![image](https://user-images.githubusercontent.com/2559382/211107154-684a6740-bab4-4737-accd-96b70d050fe2.jpeg)
