### ISSUE TITLE
Hanging Mechanism Designs

### ISSUE THREAD

**Issue by eaudiffred** [Ribbit-Network/ribbit-network-frog-hardware#171]
Opening this issue to improve our sensor hanging features. 

@muditprotect3d has already started with some great designs that can be incorporated to the sensor!  These are posted in issue #163, but we will continue the conversation here.

**Comment by eaudiffred** [comment]
@muditprotect3d, just following up on some of the designs you posted.  These two are my favorites because they seem the most versatile while remaining simple.  What ideas do you have on how to integrate them into the sensor?  Thanks again for the work you are putting into improving the hanging methods!

![image](https://user-images.githubusercontent.com/88562047/196232039-d3c9d2d8-7cc7-467b-a40e-85ef0ee5e3da.png)
![image](https://user-images.githubusercontent.com/88562047/196232073-e18085dc-1639-4c14-953d-770e7024ecb3.png)

**Comment by muditprotect3d** [comment]
<img width="1138" alt="Screen Shot 2022-11-20 at 9 43 54 PM" src="https://user-images.githubusercontent.com/106998016/202952158-bc5bfa32-05e8-451a-a5a9-1946ed2ada98.png">

**Comment by muditprotect3d** [comment]
Here is a design that I mocked up, the hooks are linear and not curved in this case but another option we could consider

**Comment by eaudiffred** [comment]
Thanks @muditprotect3d.  One concern with this is that we are currently printing the enclosure with the back flat on the print bed.  We could rotate it 90deg and have the bottom on the print bed, but then I think we will still need supports on the inside.  

What do you think about modifying the top of the head to be modular.  We could then have multiple types of hooks that the builder can choose from and attach to their frog.  Maybe some kind of block and pin?
![image](https://user-images.githubusercontent.com/88562047/203097379-42c2b76e-3e0d-4536-9b1e-1985a63c3970.png)

If the head isn't the right spot, then maybe the back of the shroud?  The multiple different hook designs you've come up with could then be interchangeable.

**Comment by muditprotect3d** [comment]
Then all I would have to do is adjust the dimensions of all the different hook designs to fit the modular fit of the head

**Comment by muditprotect3d** [comment]
https://github.com/Ribbit-Network/ribbit-network-frog-sensor/issues/163#issuecomment-1331165501

**Comment by muditprotect3d** [comment]
Moving comment over here about modular hooks @eaudiffred

**Comment by eaudiffred** [comment]
I was thinking about something like this.  But it's kind of bulky.  
![image](https://user-images.githubusercontent.com/88562047/204677945-54ad4615-ebd5-4813-93d8-744fbb218a7d.png)

**Comment by eaudiffred** [comment]
> [#163 (comment)](https://github.com/Ribbit-Network/ribbit-network-frog-sensor/issues/163#issuecomment-1331165501)

I like the idea of having multiple options for the user.  Are you thinking the frog unit would always remain the same, but then we can design different hooks that latch onto attachment points available on the frog?
Like this?  (It's very basic, but just an example)
![image](https://user-images.githubusercontent.com/88562047/204849617-5f716a6a-65e1-45b6-8e1e-40805c889907.png)

**Comment by muditprotect3d** [comment]
Yeah! This is exactly what I meant - this way the user could print whatever hook would fit best for where they want to deploy the sensor and we could make the attachment mechanisms the same

**Comment by akhilgupta1093** [comment]
One lingering thought from the meeting-- if we go with the modular hook design, depending on the difficulty, price, and how we end up shipping out the enclosures, it might make sense to print out all of the X hook options ourselves with each enclosure instead of relying on the receiver/orderer to print one of the hooks out, just to make the deployment process easier. I like the idea!

**Comment by muditprotect3d** [comment]
@akhilgupta1093 that's a good point! I think that would definitely be something important to consider for the deployment stage. Luckily the hooks should not take much time or material to use!

**Comment by muditprotect3d** [comment]
<img width="214" alt="Screen Shot 2022-12-04 at 2 34 59 PM" src="https://user-images.githubusercontent.com/106998016/205511491-61d9a020-6a5d-49c6-a498-4f4c57fce752.png">
First modular hook design! -- going to run some test prints at the end of the day and see how they all work

**Comment by muditprotect3d** [comment]
<img width="760" alt="Screen Shot 2022-12-04 at 2 55 54 PM" src="https://user-images.githubusercontent.com/106998016/205512457-67519ec6-4a1c-4b9f-b45d-abbbfbd63338.png">
Another design meant for hanging off of a flat surface

**Comment by muditprotect3d** [comment]
![85015A0E-3962-4148-94F0-E6DCEBAFC18E](https://user-images.githubusercontent.com/106998016/205754730-455ec72e-110d-43d7-91b9-e77227a348bc.jpeg)

**Comment by muditprotect3d** [comment]
![Uploading 39E999E4-D295-4796-923F-FD3327231FEC.jpeg…]()

**Comment by muditprotect3d** [comment]
Working on making the first design a little larger and come up with 1-2 more designs!

**Comment by keenanjohnson** [comment]
Looks great so far @muditprotect3d ! 

My feedback would be that I think there needs to be a larger retention feature holding the loop of the Frog Sensor's head on the hook. It sometimes gets quite windy where I am located and with the designs you've shown above, I don't feel quite confident that the wind won't blow the Frog off of the hook.

**Comment by muditprotect3d** [comment]
@keenanjohnson That's a good point ! for the second design ( wall hook) I tolerance it very tightly so it fits on with very very little movement so I think that one may be fine for that issue but I do agree the S hook would need to be bigger and have a better retention method. If you want to see what I mean with the tolerancing for the wall hook I can attach the STL file here for a test print?

**Comment by keenanjohnson** [comment]
That makes sense, however, I get nervous anytime anyone says that they specified a tight tolerance with a 3D printed part. Given the variability with different 3D printers, it always best to have a backup as well. I believe if you just added an upwards lip on the end of the arm the Frog attaches to that would be sufficient?

**Comment by keenanjohnson** [comment]
Something like this:
<img width="760" alt="205512457-67519ec6-4a1c-4b9f-b45d-abbbfbd63338" src="https://user-images.githubusercontent.com/2559382/205756514-abdf7607-3e52-44cb-aff9-4f2e8f805140.png">

**Comment by muditprotect3d** [comment]
@keenanjohnson yeah I did not think about that -- very different tolerances from printer to printer. I like that idea and can definitely do that tonight!

**Comment by keenanjohnson** [comment]
Or perhaps better yet could be some captive feature like this? 
<img width="760" alt="205512457-67519ec6-4a1c-4b9f-b45d-abbbfbd63338" src="https://user-images.githubusercontent.com/2559382/205756683-b9eb5daf-9b0c-47d6-a0f9-1998e2f1f371.png">

**Comment by muditprotect3d** [comment]
I like this -- I would have to try some test prints to make Sure the sensor can be hooked over it and have enough clearance but can definitely do that!

**Comment by muditprotect3d** [comment]
<img width="479" alt="Screen Shot 2022-12-05 at 6 56 52 PM" src="https://user-images.githubusercontent.com/106998016/205771384-a6172463-43e6-4da1-9e06-a2a3f2498476.png">
@keenanjohnson thoughts?

**Comment by muditprotect3d** [comment]
or were u thinking more of what you sent in the second picture?

**Comment by keenanjohnson** [comment]
Yeah I think that is much better!

**Comment by eaudiffred** [comment]
@muditprotect3d , awesome stuff!
A few suggestions.  First I'll mimic what you and @keenanjohnson have been discussing about the extension on the end.  Maybe try a curve so that the sensor can slide onto the hook (you don't have to worry about 90deg angles that way).  I'd also add a large gusset to the corner.  That will strengthen the shape.  
![image](https://user-images.githubusercontent.com/88562047/205788036-10b9d792-575a-42c6-b172-7f8d53f5cc9c.png)

**Comment by eaudiffred** [comment]
On the second one I would try extending the frog side of the hook as far as possible to make it as secure as possible.  I agree the top part of the S can be larger too.  
![image](https://user-images.githubusercontent.com/88562047/205788382-74c5fc0d-43b1-4c97-876d-70ed62dfeead.png)

**Comment by muditprotect3d** [comment]
@eaudiffred sorry your comments just loaded for me-- I can add that gusset shape now!, I tried to create that curve through the fillet which should make it easier to slide on but I do think completely getting rid of the 90 degree angle would be better

**Comment by muditprotect3d** [comment]
<img width="563" alt="Screen Shot 2022-12-05 at 9 38 17 PM" src="https://user-images.githubusercontent.com/106998016/205795180-910e3900-b365-4d05-b97d-1fc59dd30483.png">
@eaudiffred @keenanjohnson thoughts?

**Comment by muditprotect3d** [comment]
<img width="414" alt="Screen Shot 2022-12-06 at 12 52 31 AM" src="https://user-images.githubusercontent.com/106998016/205829067-5c74927d-5170-4a56-b230-7bd1bfdafb43.png">

**Comment by muditprotect3d** [comment]
<img width="829" alt="Screen Shot 2022-12-06 at 12 53 11 AM" src="https://user-images.githubusercontent.com/106998016/205829284-30514198-f73a-4e8c-b53a-f93122b9d6a7.png">

**Comment by muditprotect3d** [comment]
Updated designs work after talking to @eaudiffred @keenanjohnson

**Comment by muditprotect3d** [comment]
<img width="499" alt="Screen Shot 2022-12-06 at 4 08 00 PM" src="https://user-images.githubusercontent.com/106998016/206023155-0cdd6c92-cd56-4e6e-999c-dec83f61ac33.png">
action shot in assembly

**Comment by muditprotect3d** [comment]
![IMG_1747](https://user-images.githubusercontent.com/106998016/206069325-a1e04d3f-84f4-4c10-ab3e-4939d58dd24e.JPG)
![IMG_1748](https://user-images.githubusercontent.com/106998016/206069336-3bc1129b-d654-4dda-b477-454e891970e7.JPG)

**Comment by muditprotect3d** [comment]
Any feedback on these designs? @eaudiffred @keenanjohnson I think they look good, and I can send over the stl files to finalize this

**Comment by muditprotect3d** [comment]
S hook works great and increased both ends to secure it more

**Comment by muditprotect3d** [comment]
Wall hook design edited based on @eaudiffred feedback to a much better design as well

**Comment by eaudiffred** [comment]
@muditprotect3d both design look good to me.  Nice work!

**Comment by keenanjohnson** [comment]
Looks great to me! Can you share links to the Onshape files so I can add them to our repo?

**Comment by muditprotect3d** [comment]
Yup! Adding them here now

**Comment by muditprotect3d** [comment]
https://cad.onshape.com/documents/a341cd330c0b32e191922629/w/58bdc528ec1788a5da28dcfe/e/d4caabd8158b2b1764e3638f?renderMode=0&uiState=639215a071cc0f1e77ade2a5

**Comment by muditprotect3d** [comment]
Both the hooks should be a parts studio on the bottom tab

**Comment by muditprotect3d** [comment]
@keenanjohnson

**Comment by keenanjohnson** [comment]
I printed some hooks today to ship with the frog sensors going out soon and they look good! ![image](https://user-images.githubusercontent.com/2559382/206611205-fa63dd74-c9df-4754-b529-41c481dfb72d.jpeg)![Uploading 206611206...]

**Comment by keenanjohnson** [comment]
![image](https://user-images.githubusercontent.com/2559382/206611259-96d19a30-ccc6-402b-a323-b4fd0ef328c2.jpeg)

**Comment by keenanjohnson** [comment]
@muditprotect3d I have created a new Ribbit Network team in Onshape. Can you share your document with the team? You should be able to do that from the Share menu in the doc:
<img width="688" alt="image" src="https://user-images.githubusercontent.com/2559382/206611499-19dd74b1-6bb6-44a8-b68b-1472dd930c5b.png">


Also what Onshape email do you use and I can add you to the team. 

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/2559382/206611403-022dd3a3-c751-4ed1-809d-6ac0e7ef56fa.png">

**Comment by keenanjohnson** [comment]
Yes perfect!

**Comment by keenanjohnson** [comment]
Closing this out for now. Let's make issues for individual improvements as we think of them.
