### ISSUE TITLE
V4: Assembly Instruction Updates

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-frog-hardware#190]

**Comment by keenanjohnson** [comment]
I've created this branch which includes the initial BOM, mechanical files and copied assembly instructions. 

The assembly instructions of course need to be updated for V4. 

https://github.com/Ribbit-Network/ribbit-network-frog-hardware/tree/v4

**Comment by eaudiffred** [comment]
PR #194 submitted.  Looks like @keenanjohnson has reviewed and merged, thanks!
