### ISSUE TITLE
Enclosure: PoE Support for V4 Frog Sensor

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-frog-hardware#204]
In order to support a test at an Ameriflux monitoring station, we need to create a version of the Frog Sensor that supports Power over Ethernet (PoE).

@damz has been doing good work supporting a [Power over Ethernet module in Software](https://github.com/Ribbit-Network/ribbit-network-frog-software/pull/32), but we will need to modify the enclosure to support this as well.

### Hardware Selection
The PoE Featherwing from Silicognition is the selected hardware that allows data and power over the ethernet connector in a featherwing form-factor. 

This board can be purchased from several places:

* [Amazon](https://www.amazon.com/gp/product/B08KTVD7BR/ref=sw_img_1?smid=A3MSGSZ93QJG1S&psc=1)
* [Mouser](https://www.mouser.com/ProductDetail/Silicognition/CS-POEFEATHER-01?qs=hWgE7mdIu5QddMUXdZnt2A%3D%3D&gclid=CjwKCAiA_vKeBhAdEiwAFb_nrX0lzXUKBNW3-cXWsQ_DCekkhhjqKgbTiD1w3G7DzInxcdu0xdi_4BoChnUQAvD_BwE) 

@keenanjohnson and @damz both have testing modules.

### Enclosure Modification

@damz provided the image below showing that the board will obviously not fit in the current enclosure.

![image](https://user-images.githubusercontent.com/2559382/216699245-7885b097-90c7-442d-a65b-4547df5b1671.png)

It seems that the enclosure will need to become deeper to support the added height of the ethernet connector.

The other big decision is whether to turn the microcontroller and PoE hat so that the cable comes out of the bottom or route the cable out of the side of the enclosure using a cable gland.

### Scalability

This design is initially for a one-off test, so I'm not so worried about it being easy to produce or anything.

**Comment by keenanjohnson** [comment]
It doesn't seem like there is a cad model available for this board on any sites I could find. I sent a message asking if the vendor could provide us with a 3d model.

**Comment by keenanjohnson** [comment]
@spestana just thought of this, but I wanted to confirm that the Windriver site is using a standard RJ-45 ethernet cable right?

**Comment by keenanjohnson** [comment]
Let me know if you need specific other dimensions @eaudiffred !

**Comment by eaudiffred** [comment]
@keenanjohnson, Thanks for all the info!  Looks good.  I'll be able to dive in this weekend and make the modifications.

**Comment by keenanjohnson** [comment]
Thanks!

**Comment by eaudiffred** [comment]
@keenanjohnson, would you be able to take some measurement pictures of the PoE wing and ESP feather connected?  Then I can get an idea of the whole unit dimension.

**Comment by eaudiffred** [comment]
@keenanjohnson @spestana 
Here is what I have so far.  Maybe we call this one Bull Frog...It's huge, lol!  Let me know what you think about placement and routing.
https://cad.onshape.com/documents/b3e6eeabf50d585d20f25fc6/w/a4a82302d129f025f23b244a/e/d204eaabda9d0f822641f52b
![image](https://user-images.githubusercontent.com/88562047/218277370-7557059d-b214-4030-a9b4-c4ce34f4b72f.png)
![image](https://user-images.githubusercontent.com/88562047/218277385-25e7dac8-1906-4ddb-84f3-d98ea0c508b4.png)
![image](https://user-images.githubusercontent.com/88562047/218277391-4ff39a5b-7b77-4315-a9c1-db5a3b14ba5a.png)

**Comment by keenanjohnson** [comment]
Haha yeah Bull Frog is a great name. Looks good to me in general shape. 

I think the connector hole on the bottom might need to be larger to allow the ethernet cable to fit through?

I've attached some photos of the stackup. The total height seems to be about 30 mm and the length is about 60 mm.

![IMG_9364](https://user-images.githubusercontent.com/2559382/218331859-3bda27f4-9946-4f51-85d3-638b40302c1b.jpg)
![IMG_9365](https://user-images.githubusercontent.com/2559382/218331861-9c7f5548-ee6c-4678-b1b3-a69a0af3b4af.jpg)

**Comment by eaudiffred** [comment]
@keenanjohnson, great, thanks for those measurements!  Based on those I was able to shrink it up a little.  I just went ahead and made a separate hole for the ethernet cable.

**Comment by spestana** [comment]
Thanks for you work on this @eaudiffred , it looks great. @keenanjohnson do you think we're still on track to send off the hardware by end of March?

**Comment by keenanjohnson** [comment]
I believe so! I have all the electronics required here and enough filamint to print an enclosure whenever we are ready! Just let me know when the time is right @eaudiffred!

**Comment by eaudiffred** [comment]
@keenanjohnson, Ready for a print.  
[FrogV4_POE.zip](https://github.com/Ribbit-Network/ribbit-network-frog-hardware/files/10831423/FrogV4_POE.zip)

**Comment by keenanjohnson** [comment]
Thanks @eaudiffred ! I won't have time to print this for another week or two due to travel, but that should still be plenty of time to print and test before April 1.

**Comment by keenanjohnson** [comment]
Starting a test print now!

**Comment by eaudiffred** [comment]
Sounds good.  I've added screw holes for at all four posts.

**Comment by eaudiffred** [comment]
@keenanjohnson 
[FrogV4_POE.zip](https://github.com/Ribbit-Network/ribbit-network-frog-hardware/files/11045574/FrogV4_POE.zip)

**Comment by eaudiffred** [comment]
Have you tried the other components?  Everything is scaled, so functionally it should be the same.

**Comment by keenanjohnson** [comment]
Yup everything else looks great :)

**Comment by eaudiffred** [comment]
@keenanjohnson, is there anything else we need to complete on this one?

**Comment by keenanjohnson** [comment]
Nope! let's close it out! Thanks for your help!
