### ISSUE TITLE
Enclosure Mounting: Pole

### ISSUE THREAD

**Issue by eaudiffred** [Ribbit-Network/ribbit-network-frog-hardware#205]
Refine the mounting option for a post/pole.

**Comment by eaudiffred** [comment]
I think this will work.  I have a final test print running now.
@keenanjohnson,  Linked here:
https://cad.onshape.com/documents/b3e6eeabf50d585d20f25fc6/w/a4a82302d129f025f23b244a/e/bb2bd1948feb925547304752
I'm just using standard zip ties.
![20230209_205809](https://user-images.githubusercontent.com/88562047/217997482-4aae1644-120e-421e-9cdd-4bcd54e65215.jpg)
![20230209_205816](https://user-images.githubusercontent.com/88562047/217997488-53aac491-9066-4353-969b-3fb089eef764.jpg)

![20230209_205802](https://user-images.githubusercontent.com/88562047/217997545-6235c7da-a5be-4d03-ad5d-2f93b713f38a.jpg)

**Comment by keenanjohnson** [comment]
Looks great @eaudiffred! Let me know how the final test print goes and we can start printing some to include in the Trane kits!

**Comment by eaudiffred** [comment]
@keenanjohnson it turned out well!  I started a larger batch this morning.
