### ISSUE TITLE
Suggestion: add an Adafruit wishlist to BOM for easy part ordering

### ISSUE THREAD

**Issue by jtcomp** [Ribbit-Network/ribbit-network-frog-hardware#208]
Ie: https://www.adafruit.com/wishlists/569099

This would let people just "add all" to their cart rather than having to go down the BOM manually
<img width="1067" alt="Screenshot 2023-02-24 at 12 16 24 PM" src="https://user-images.githubusercontent.com/5924203/221282429-1458cbf0-dbba-47fa-b715-ffae1904bb63.png">

**Comment by keenanjohnson** [comment]
Good suggestion @jtcomp ! Is that something you would be interested in helping out with?

**Comment by legendsjohn** [comment]
Yeah, I can create PRs with links

**Comment by keenanjohnson** [comment]
Thanks @legendsjohn !

**Comment by eaudiffred** [comment]
Added the wishlist the parts instructions.  #215

**Comment by keenanjohnson** [comment]
Done! Thanks @eaudiffred !
