### ISSUE TITLE
USB Right Angle Connectors Don't Always Insert All The Way

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-frog-hardware#209]
I noticed when inspecting the sensors from the recent large order that there seems to be some tolerance differences in either the enclosures or the USB right angle connectors. Some of the connectors would not insert fully into the connector. 

I am sure what the right way to solve this is. Perhaps the braces only need to support the connector on the top and right, but not the left side? 

![image](https://user-images.githubusercontent.com/2559382/227057795-5db84429-528c-4919-9467-1bf41b9b87aa.jpeg)

**Comment by eaudiffred** [comment]
This is a tricky one.  I noticed the same thing.  I purchased a few different brands of USBC right angle connectors, and each was slightly different dimensionally.  
We could eliminate the top support.  The right support helps keep it straight.  The left support is doing all the heavy lifting though - the connector is resting on that one as the power cord pulls down.  
We could try and shift it to the left more.  It would sit less on the plastic body and more on the metal, but I think that's ok.  
![image](https://user-images.githubusercontent.com/88562047/228246367-1f825630-265e-4d7e-81dd-8441de930d73.png)
We still have the option to go back to the zip-tie, but that adds parts.

**Comment by eaudiffred** [comment]
Maybe we should instead release the tension on the power cable form being applied to that point.  If we had some sort of clip on the bottom of the base for the power cord, it could relieve the tension and eliminate the need for the supports inside the base.  
![image](https://user-images.githubusercontent.com/88562047/228247893-573c9253-af05-4426-abcd-03fd1ea6c22d.png)

**Comment by eaudiffred** [comment]
I removed the top support and shifted the left support 0.6mm to the left for more clearance.  I also added a cable clip that we can experiment with.
![image](https://user-images.githubusercontent.com/88562047/235700532-eb4dbc64-00b6-4060-8e95-9060c477163b.png)
![image](https://user-images.githubusercontent.com/88562047/235700633-fe79d51a-0621-4fe2-b77a-0d74007d6390.png)

**Comment by josuah** [comment]
This might also help with robustness: the USB connector is often the first thing to break in any device.
Type-C might have a better rating, in practice, it is still fragile.

Something that laptop does for instance, is a cable plugged to the internal connector (barebone pins) and an actual connector *screwed* to the enclosure.

Some very small cable would eliminate any form of strain onto the soldered connector of the devboard.

**Comment by josuah** [comment]
To take the same supplier:
- https://www.adafruit.com/product/4218 - $9.95 - panel mount cable
- https://www.adafruit.com/product/4432 - $3.95 - Angle adapter

The current solution wins by the price.
Though, if changing it, I'd still consider adding plenty of support to limit the strain:
![235700532-eb4dbc64-00b6-4060-8e95-9060c477163b](https://user-images.githubusercontent.com/55351021/235787295-6d763b24-f63a-41c0-a36e-34ec286c4e92.png)

Good idea though!

**Comment by eaudiffred** [comment]
Here is the latest idea I have.  This gets the pulling force off of the adapter.  

![image](https://github.com/Ribbit-Network/ribbit-network-frog-hardware/assets/88562047/1edf0253-91e3-4be6-9fb9-831687a2ea96)
![image](https://github.com/Ribbit-Network/ribbit-network-frog-hardware/assets/88562047/a5e936a0-c843-48a6-a120-5eaffba4ef5a)
![image](https://github.com/Ribbit-Network/ribbit-network-frog-hardware/assets/88562047/7df7115b-f626-4c23-b19a-3e05d53978fb)

**Comment by keenanjohnson** [comment]
Wow looks great to me!

**Comment by josuah** [comment]
> I also added a cable clip
Now I see better what this means.
That sounds quite robust!

**Comment by eaudiffred** [comment]
> 

I think it will relieve any pressure from the USBC connection.  I did order one of those panel mount USBC connectors that you linked above.  I like that idea better than the right angle connector, I'm just worried about space requirements.  It's supposed to show up tomorrow, so we'll see how it fits.
