### ISSUE TITLE
Sensors Cables Are Easy to Squish When Clipping on the Head

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-frog-hardware#210]
When looking at the finished sensors after our workshop, a small number had squished sensor cables as shown which prevented them from working correctly. ![image](https://user-images.githubusercontent.com/2559382/227058338-61d6d9db-79dc-45a4-b548-b242444f7ae5.jpeg)

**Comment by muditprotect3d** [comment]
Making the notch would remove the stress from the lid on those and it wouldn't increase the size of the enclosure either, I think that could be the most optimal solution

**Comment by eaudiffred** [comment]
Added two small notches for cable routing.  One notch on the base, one on the shroud.

**Comment by eaudiffred** [comment]
Adding a couple pictures to show the results:
![image](https://github.com/Ribbit-Network/ribbit-network-frog-hardware/assets/88562047/2aa874b8-daa9-40b1-9ec4-ce79cf6cf7b6)
![image](https://github.com/Ribbit-Network/ribbit-network-frog-hardware/assets/88562047/a6f9b78d-8111-435d-8b28-1288d469a5d5)

**Comment by keenanjohnson** [comment]
I like it!
