### ISSUE TITLE
Microcontroller Can Lift Up When Screws are Inserted

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-frog-hardware#211]
We only have screws in two of the four holes on the microcontroller which are both located on the side nearest the USB Connector.

This can often result in the microcontroller's opposite side lifting off of the locating pins when the screws are tightened. I noticed this when inspecting some of the units after our last corporate event. 

This is not ideal as it adds strain on the USB connector.

I'm not sure if the right solution is to go back to four screws or explore the slot idea we have previously explored.

**Comment by muditprotect3d** [comment]
I can give it a try with the sliding mechanism if we decide that's the solution we want to go with, but from what I remember when we tried this in December one of the issues was fitting the carrier board in too

**Comment by eaudiffred** [comment]
What if instead of locator pins we created a backstop with a notch.  Kind of combining the sliding idea and locator idea.  This way we can keep the enclosure the same size and also not have to add more screws.  

![image](https://user-images.githubusercontent.com/88562047/235165453-6a0f4270-233a-490e-930e-5f9fd63e0906.png)

**Comment by keenanjohnson** [comment]
That looks like a much better concept to me!

The only issue is that it creates an overhang for the 3D printing. In my
experience we shouldn’t have issues 3D printing it and we could make the
overhang notch rounded instead of right angles to re risk it further.

**Comment by eaudiffred** [comment]
Yeah, good point.  Maybe something like this:
![image](https://user-images.githubusercontent.com/88562047/235695143-2fd0aae6-3d61-4220-8aec-af85c48c212b.png)

**Comment by keenanjohnson** [comment]
Yeah that's exactly what I was thinking!

**Comment by eaudiffred** [comment]
Test prints turned out well.  This along with the cable clip reduces the force on the adapter and frees up the stress on the board.

**Comment by keenanjohnson** [comment]
Perfect!
