### ISSUE TITLE
Head Clips Can Sometimes Break Off 

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-frog-hardware#212]
Several groups assembling Frog Sensors during our last corporate event reported that their head clips broke off during assembly. 

This may be related to poor 3D printing quality for some of our parts in the last order, but perhaps there is also something we should consider to make the design more robust to that?

![image003](https://user-images.githubusercontent.com/2559382/227059595-d72b59bd-ae42-4a1b-94cc-71e614111adc.jpg)

**Comment by eaudiffred** [comment]
Thanks for getting pictures @keenanjohnson!  I'm thinking some fillet work could help this problem.

**Comment by muditprotect3d** [comment]
Agreed @eaudiffred filleting those edges would reduce some of the stress flow coming down on them when they are being forced in

**Comment by eaudiffred** [comment]
Added some fillets to the outside of the clips.  This may need a few test prints to fine tune.  
![image](https://user-images.githubusercontent.com/88562047/231005376-20adc2d5-1ca4-44c9-8f5c-43dcfbe05f31.png)

**Comment by eaudiffred** [comment]
Just finished a test print.  This turned out well.  I was able to apply a lot of pressure to the clip tab without it snapping.

**Comment by keenanjohnson** [comment]
Sounds awesome @eaudiffred ! I've reopened this just so we can commit the updated parts. Can you attach them here or open a PR with them?

**Comment by eaudiffred** [comment]
Yes!  I'll submit a PR with all of the updated V4 parts once they are complete.
