### ISSUE TITLE
V4 Lid Redesign

### ISSUE THREAD

**Issue by eaudiffred** [Ribbit-Network/ribbit-network-frog-hardware#216]
The lid design needs to be redesigned to eliminate the tab and make it easier to take on/off.

**Comment by eaudiffred** [comment]
Adding some info @muditprotect3d shared in discord:
![image](https://github.com/Ribbit-Network/ribbit-network-frog-hardware/assets/88562047/6cb4a271-c139-45fb-9795-fc9fba6eabbe)

**Comment by eaudiffred** [comment]
@muditprotect3d I used that idea and applied it to the frog sensor lid.  I think it works great!  Awesome idea!

![image](https://github.com/Ribbit-Network/ribbit-network-frog-hardware/assets/88562047/48cc7179-21ef-416b-8815-d0e814535f35)

**Comment by eaudiffred** [comment]
The test print turned out great!

![WIN_20230521_09_57_52_Pro](https://github.com/Ribbit-Network/ribbit-network-frog-hardware/assets/88562047/b7e3e7ee-e73f-4993-b73b-45de87c0b24d)
![WIN_20230521_09_58_46_Pro](https://github.com/Ribbit-Network/ribbit-network-frog-hardware/assets/88562047/650fdba5-f7ca-4c2b-a542-5d4d6a801795)
![WIN_20230521_09_58_55_Pro](https://github.com/Ribbit-Network/ribbit-network-frog-hardware/assets/88562047/32dbb1ce-207a-49af-9a62-a96a9773be9e)

**Comment by keenanjohnson** [comment]
Oh that's really interesting! Seems like it could be a more robust design to tolerance differences in different printers / filemint brands, etc

**Comment by eaudiffred** [comment]
After a few test prints I'm pretty happy with the results!  Here are the STL files if anyone wants to try it out.  
[Base_Lid_V4.zip](https://github.com/Ribbit-Network/ribbit-network-frog-hardware/files/11578362/Base_Lid_V4.zip)

**Comment by keenanjohnson** [comment]
Cool. I'll do a test print here.

**Comment by eaudiffred** [comment]
@keenanjohnson, how did it turn out?  What are your thoughts?

**Comment by keenanjohnson** [comment]
I really like the concept and it slides on really well!

I think we might need to add a feature to stop the sliding in one direction though, so it's easy to just slide on the lid until you hit the feature.

My lid slides around all over the place haha. https://github.com/Ribbit-Network/ribbit-network-frog-hardware/assets/2559382/8b23278f-0735-402e-ab14-482474135e9c

**Comment by eaudiffred** [comment]
Looks like differences in printer tolerances again.  The few I've printed aren't so free floating.  Thanks for printing a set.  I'll think about how we can incorporate a stop.  Maybe just stopping the tracks on the base.

**Comment by keenanjohnson** [comment]
Ah I see. That's the benefit of collaboration between us :)

**Comment by eaudiffred** [comment]
A small change, but I think it will be effective in limiting the slide through.  
![image](https://github.com/Ribbit-Network/ribbit-network-frog-hardware/assets/88562047/3e6b3466-a65b-43a2-8e70-1512ac41dd6b)
![image](https://github.com/Ribbit-Network/ribbit-network-frog-hardware/assets/88562047/3116c868-ddd9-46c6-91c3-49557ee0aae6)
![image](https://github.com/Ribbit-Network/ribbit-network-frog-hardware/assets/88562047/e4803a59-c203-4d78-a3a1-d6e78936e636)
![image](https://github.com/Ribbit-Network/ribbit-network-frog-hardware/assets/88562047/a76ca497-5c92-46dd-99c2-5c060e0652da)

**Comment by keenanjohnson** [comment]
Looks perfect to me! Like you said, I don't think much is needed there.

**Comment by eaudiffred** [comment]
[Base_Lid_V4.zip](https://github.com/Ribbit-Network/ribbit-network-frog-hardware/files/11593401/Base_Lid_V4.zip)
Here are the file if you have time to run a test today.  I'm going to start one now.

**Comment by keenanjohnson** [comment]
Will start a test now!

**Comment by keenanjohnson** [comment]
Looks much better to me now.

https://github.com/Ribbit-Network/ribbit-network-frog-hardware/assets/2559382/1adf828f-adc4-4f4b-b18c-379c9a8d9724

Lid locates well.

**Comment by eaudiffred** [comment]
@keenanjohnson, that video shows the lid still being able to slide freely off of both sides.  Is that previous version?  
I was hoping that the little notch and step would create a point at which the lid could no longer slide to the left.

**Comment by keenanjohnson** [comment]
Oh whoops. I guess I didn't take a new video. Anyway, it works great as you would expect.
