### ISSUE TITLE
Add More Visible Status LED to Frog Sensor

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-frog-hardware#59]
One of the common complaints about the Frog Sensor is that it is difficult to quickly determine the status of the sensor (is there an error? Is it connected to wifi, etc).

It's been suggested that the simplest first effort at solving this would be to add a status LED that is visible from the outside of the enclosure to display the Frog Status.

**Comment by keenanjohnson** [comment]
It seems like the most promising option would be to add one of these WS2813 LEDs. This one from SEED studios comes on a board and has a nice i2c connector already.

https://www.mouser.com/ProductDetail/Seeed-Studio/104020169?qs=BJlw7L4Cy7%2FQJGgijlqWzg%3D%3D

![image](https://user-images.githubusercontent.com/2559382/142962490-605baf96-70e1-4525-bd8d-82d606c3da31.png)

Now a mounting location just needs to be decided. Perhaps up in the sensor shroud so that light comes out of the openings could be nice. I'll try to see if it fits in CAD.

**Comment by keenanjohnson** [comment]
As discussed on Discord, @lwbantoto is going to take over this task :). Thanks!

**Comment by lwbantoto** [comment]
Commenting @keenanjohnson

**Comment by keenanjohnson** [comment]
It's my belief that the local user interface will be more useful than an LED. Closing as won't fix for now.
